language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
- rustup component add clippy rustfmt
script:
- cargo fmt -- --check
- cargo clippy
- cargo build
- cargo test